export const MAIN_URL = `${process.env.APPLICATION_BFF_URL}`;

export const LEVEL_1_REQUEST = 'LEVEL_1_REQUEST';
export const LEVEL_1_RECIEVE_ERROR = 'LEVEL_1_RECIEVE_ERROR';
export const LEVEL_1_RECIEVE = 'LEVEL_1_RECIEVE';

export const ALL_CATEGORIES_REQUEST = 'ALL_CATEGORIES_REQUEST';
export const ALL_CATEGORIES_RECIEVE_ERROR = 'ALL_CATEGORIES_RECIEVE_ERROR';
export const ALL_CATEGORIES_RECIEVE = 'ALL_CATEGORIES_RECIEVE';
