export const MAIN_URL = `${process.env.APPLICATION_BFF_URL}`;

export const CUSTOMER_REQUEST = 'CUSTOMER_REQUEST';
export const CUSTOMER_RECIEVE_ERROR = 'CUSTOMER_RECIEVE_ERROR';
export const CUSTOMER_RECIEVE = 'CUSTOMER_RECIEVE';

export const CUSTOMER_FORM_REQUEST = 'CUSTOMER_FORM_REQUEST';
export const CUSTOMER_FORM_RECIEVE_ERROR = 'CUSTOMER_FORM_RECIEVE_ERROR';
export const CUSTOMER_FORM_RECIEVE = 'CUSTOMER_FORM_RECIEVE';

