export const EMPLOYEES_URL = `${process.env.APPLICATION_BFF_URL}`

export const REQUEST_EMPLOYEES_LIST = 'REQUEST_EMPLOYEES_LIST';
export const RECEIVE_EMPLOYEES_LIST = 'RECEIVE_EMPLOYEES_LIST';
export const RECEIVE_EMPLOYEES_LIST_ERROR = 'RECEIVE_EMPLOYEES_LIST_ERROR';
