export const EMPLOYEES_URL = `${process.env.APPLICATION_BFF_URL}`
export const EMPLOYEE_MEDIAL_URL = `${process.env.MEDIA_SERVICE_ADDRESS}`

export const REQUEST_EMPLOYEES_LIST = 'REQUEST_EMPLOYEES_LIST';
export const RECEIVE_EMPLOYEES_LIST = 'RECEIVE_EMPLOYEES_LIST';
export const RECEIVE_EMPLOYEES_LIST_ERROR = 'RECEIVE_EMPLOYEES_LIST_ERROR';

export const REQUEST_EMPLOYEES_LIST_CSV_UPLOAD = 'REQUEST_EMPLOYEES_LIST_CSV_UPLOAD';
export const RECEIVE_EMPLOYEES_LIST_CSV_UPLOAD = 'RECEIVE_EMPLOYEES_LIST_CSV_UPLOAD';
export const RECEIVE_EMPLOYEES_LIST_CSV_UPLOAD_ERROR = 'RECEIVE_EMPLOYEES_LIST_CSV_UPLOAD_ERROR';
