export const INVENTORY_URL = `${process.env.APPLICATION_BFF_URL}`

export const REQUEST_INVENTORY_LOOKUP_DATA = 'REQUEST_INVENTORY_LOOKUP_DATA';
export const RECEIVE_INVENTORY_LOOKUP_DATA = 'RECEIVE_INVENTORY_LOOKUP_DATA';
export const RECEIVE_INVENTORY_LOOKUP_DATA_ERROR = 'RECEIVE_INVENTORY_LOOKUP_DATA_ERROR';

export const REQUEST_INVENTORY_DATA = 'REQUEST_INVENTORY_DATA';
export const RECEIVE_INVENTORY_DATA = 'RECEIVE_INVENTORY_DATA';
export const RECEIVE_INVENTORY_DATA_ERROR = 'RECEIVE_INVENTORY_DATA_ERROR';

export const REQUEST_INVENTORY_UPDATE = 'REQUEST_INVENTORY_UPDATE';
export const RECEIVE_INVENTORY_UPDATE = 'RECEIVE_INVENTORY_UPDATE';
export const RECEIVE_INVENTORY_UPDATE_ERROR = 'RECEIVE_INVENTORY_UPDATE_ERROR';


