export const OVERRIDE_LOOKUP_URL = `${process.env.APPLICATION_BFF_URL}`

export const INIT_PRODUCT_OVERRIDE = 'INIT_PRODUCT_OVERRIDE'
export const RECEIVE_PRODUCT_OVERRIDE = 'RECEIVE_PRODUCT_OVERRIDE'
export const RECEIVE_PRODUCT_OVERRIDE_ERROR = 'RECEIVE_PRODUCT_OVERRIDE_ERROR'

export const REQUEST_PRODUCT_DATA = 'REQUEST_PRODUCT_DATA'
export const RECEIVE_PRODUCT_DATA = 'RECEIVE_PRODUCT_DATA'
export const RECEIVE_PRODUCT_DATA_ERROR = 'RECEIVE_PRODUCT_DATA_ERROR'

export const SEND_SELECTED_PRODUCTS = 'SEND_SELECTED_PRODUCTS'