export const PURCHASE_ORDERS_URL = `${process.env.APPLICATION_BFF_URL}`

export const REQUEST_PURCHASE_ORDERS = 'REQUEST_PURCHASE_ORDERS';
export const RECEIVE_PURCHASE_ORDERS = 'RECEIVE_PURCHASE_ORDERS';
export const RECEIVE_PURCHASE_ORDERS_ERROR = 'RECEIVE_PURCHASE_ORDERS_ERROR';

export const REQUEST_PURCHASE_ORDER_SAVE = 'REQUEST_PURCHASE_ORDER_SAVE';
export const RECEIVE_PURCHASE_ORDER_SAVE = 'RECEIVE_PURCHASE_ORDER_SAVE';
export const RECEIVE_PURCHASE_ORDER_SAVE_ERROR = 'RECEIVE_PURCHASE_ORDER_SAVE_ERROR';

export const REQUEST_PURCHASE_ORDER_BY_ID = 'REQUEST_PURCHASE_ORDER_BY_ID';
export const RECEIVE_PURCHASE_ORDER_BY_ID = 'RECEIVE_PURCHASE_ORDER_BY_ID';
export const RECEIVE_PURCHASE_ORDER_BY_ID_ERROR = 'RECEIVE_PURCHASE_ORDER_BY_ID_ERROR';

export const REQUEST_PO_REQUISITION_UPDATE = 'REQUEST_PO_REQUISITION_UPDATE';

export const SET_PO_VIEW_FLAG = 'SET_PO_VIEW_FLAG';

export const REQUEST_PURCHASE_ORDER_RECIEPT_BY_ID = 'REQUEST_PURCHASE_ORDER_RECIEPT_BY_ID';
export const RECEIVE_PURCHASE_ORDER_RECIEPT_BY_ID = 'RECEIVE_PURCHASE_ORDER_RECIEPT_BY_ID';
export const RECEIVE_PURCHASE_ORDER_RECIEPT_BY_ID_ERROR = 'RECEIVE_PURCHASE_ORDER_RECIEPT_BY_ID_ERROR';

export const REQUEST_PO_RECIEPT_REQUISITION_UPDATE = 'REQUEST_PO_RECIEPT_REQUISITION_UPDATE';