export const PRODUCT_LOOKUP_URL = `${process.env.APPLICATION_BFF_URL}`

export const REQUEST_PRODUCT_VOLUME_DATA = 'REQUEST_PRODUCT_VOLUME_DATA';
export const RECEIVE_PRODUCT_VOLUME_DATA = 'RECEIVE_PRODUCT_VOLUME_DATA';

export const REQUEST_PRODUCT_REVENUE_DATA = 'REQUEST_PRODUCT_REVENUE_DATA';
export const RECEIVE_PRODUCT_REVENUE_DATA = 'RECEIVE_PRODUCT_REVENUE_DATA';

export const REQUEST_PRODUCT_PROFIT_DATA = 'REQUEST_PRODUCT_PROFIT_DATA';
export const RECEIVE_PRODUCT_PROFIT_DATA = 'RECEIVE_PRODUCT_PROFIT_DATA';

export const REQUEST_PRODUCT_ALL_DATA = 'REQUEST_PRODUCT_ALL_DATA';
export const RECEIVE_PRODUCT_ALL_DATA = 'RECEIVE_PRODUCT_ALL_DATA';

export const REQUEST_PRODUCT_WISE_VOLUME_DATA = 'REQUEST_PRODUCT_WISE_VOLUME_DATA';
export const RECEIVE_PRODUCT_WISE_VOLUME_DATA = 'RECEIVE_PRODUCT_WISE_VOLUME_DATA';

export const REQUEST_PRODUCT_WISE_REVENUE_DATA = 'REQUEST_PRODUCT_WISE_REVENUE_DATA';
export const RECEIVE_PRODUCT_WISE_REVENUE_DATA = 'RECEIVE_PRODUCT_WISE_REVENUE_DATA';

export const REQUEST_PRODUCT_WISE_PROFIT_DATA = 'REQUEST_PRODUCT_WISE_PROFIT_DATA';
export const RECEIVE_PRODUCT_WISE_PROFIT_DATA = 'RECEIVE_PRODUCT_WISE_PROFIT_DATA';

export const REQUEST_CUSTOMER_DATA = 'REQUEST_CUSTOMER_DATA';
export const RECEIVE_CUSTOMER_DATA = 'RECEIVE_CUSTOMER_DATA';

export const REQUEST_INVENTORY_DATA = 'REQUEST_INVENTORY_DATA';
export const RECEIVE_INVENTORY_DATA = 'RECEIVE_INVENTORY_DATA';

export const REQUEST_SALE_BY_STORE_DATA = 'REQUEST_SALE_BY_STORE_DATA';
export const RECEIVE_SALE_BY_STORE_DATA = 'RECEIVE_SALE_BY_STORE_DATA';

export const REQUEST_TOP_PRODUCTS = 'REQUEST_TOP_PRODUCTS';
export const RECEIVE_TOP_PRODUCTS = 'RECEIVE_TOP_PRODUCTS';

export const REQUEST_EMP_PAYROLL_DEDUCT_DETAILS = 'REQUEST_EMP_PAYROLL_DEDUCT_DETAILS';
export const RECEIVE_EMP_PAYROLL_DEDUCT_DETAILS = 'RECEIVE_EMP_PAYROLL_DEDUCT_DETAILS';
export const RECEIVE_EMP_PAYROLL_DEDUCT_DETAILS_ERROR = 'RECEIVE_EMP_PAYROLL_DEDUCT_DETAILS_ERROR';

export const REQUEST_EMP_PAYROLL_DEDUCT_SUMMARY = 'REQUEST_EMP_PAYROLL_DEDUCT_SUMMARY';
export const RECEIVE_EMP_PAYROLL_DEDUCT_SUMMARY = 'RECEIVE_EMP_PAYROLL_DEDUCT_SUMMARY';
export const RECEIVE_EMP_PAYROLL_DEDUCT_SUMMARY_ERROR = 'RECEIVE_EMP_PAYROLL_DEDUCT_SUMMARY_ERROR';

export const REQUEST_EMP_DISCOUNT_REPORT = 'REQUEST_EMP_DISCOUNT_REPORT';
export const RECEIVE_EMP_DISCOUNT_REPORT = 'RECEIVE_EMP_DISCOUNT_REPORT';
export const RECEIVE_EMP_DISCOUNT_REPORT_ERROR = 'RECEIVE_EMP_DISCOUNT_REPORT_ERROR';

export const REQUEST_EMP_DETAILS_LIST = 'REQUEST_EMP_DETAILS_LIST';
export const RECEIVE_EMP_DETAILS_LIST = 'RECEIVE_EMP_DETAILS_LIST';
export const RECEIVE_EMP_DETAILS_LIST_ERROR = 'RECEIVE_EMP_DETAILS_LIST_ERROR';





