export const MAIN_URL = `${process.env.APPLICATION_BFF_URL}`;

export const REQUEST_RETAILER_LIST = 'REQUEST_RETAILER_LIST';
export const RECIEVE_RETAILER_LIST = 'RECIEVE_RETAILER_LIST';
export const RECIEVE_RETAILER_LIST_ERROR = 'RECIEVE_RETAILER_LIST_ERROR';

export const REQUEST_SAVE_RETAILER_DATA = 'REQUEST_SAVE_RETAILER_DATA';
export const RECIEVE_SAVE_RETAILER_DATA = 'RECIEVE_SAVE_RETAILER_DATA';
export const RECIEVE_SAVE_RETAILER_DATA_ERROR = 'RECIEVE_SAVE_RETAILER_DATA_ERROR';
