export const MAIN_URL = `${process.env.APPLICATION_BFF_URL}`;

export const INIT_CREATE_RP_EARNING_RULE = 'INIT_CREATE_RP_EARNING_RULE';
export const SUCCESS_CREATE_RP_EARNING_RULE = 'SUCCESS_CREATE_RP_EARNING_RULE';
export const FAILED_CREATE_RP_EARNING_RULE = 'FAILED_CREATE_RP_EARNING_RULE';

export const INIT_CREATE_RP_REDEEMPTION_RULE = 'INIT_CREATE_RP_REDEEMPTION_RULE';
export const SUCCESS_CREATE_RP_REDEEMPTION_RULE = 'SUCCESS_CREATE_RP_REDEEMPTION_RULE';
export const FAILED_CREATE_RP_REDEEMPTION_RULE = 'FAILED_CREATE_RP_REDEEMPTION_RULE';