export const RULE_URL = `${process.env.APPLICATION_BFF_URL}`;
export const REQUEST_REWARD_EARN_RULE = 'REQUEST_REWARD_EARN_RULE';
export const RECEIVED_REWARD_EARN_RULE = 'RECEIVED_REWARD_EARN_RULE';
export const RECEIVED_REWARD_EARN_RULE_ERROR = 'RECEIVED_REWARD_EARN_RULE_ERROR';
export const REQUEST_REWARD_EARN_RULE_DATA = 'REQUEST_REWARD_EARN_RULE_DATA';
export const RECEIVED_REWARD_EARN_RULE_DATA = 'RECEIVED_REWARD_EARN_RULE_DATA';
export const RECEIVED_REWARD_EARN_RULE_DATA_ERROR = 'RECEIVED_REWARD_EARN_RULE_DATA_ERROR';
