export const SESSION_URL = `${process.env.APPLICATION_BFF_URL}`;
export const REQUEST_SESSION_LIST = 'REQUEST_SESSION_LIST';
export const RECEIVED_SESSION_LIST = 'RECEIVED_SESSION_LIST';
export const RECEIVED_SESSION_LIST_ERROR = 'RECEIVED_SESSION_LIST_ERROR';

export const REQUEST_SESSION_DATA = 'REQUEST_SESSION_DATA';
export const RECEIVED_SESSION_DATA = 'RECEIVED_SESSION_DATA';
export const RECEIVED_SESSION_DATA_ERROR = 'RECEIVED_SESSION_DATA_ERROR';

export const REQUEST_SESSION_ADD_EDIT = 'REQUEST_SESSION_ADD_EDIT';
export const RECEIVED_SESSION_ADD_EDIT = 'RECEIVED_SESSION_ADD_EDIT';
export const RECEIVED_SESSION_ADD_EDIT_ERROR = 'RECEIVED_SESSION_ADD_EDIT_ERROR';

export const REQUEST_SESSION_PUT_MONEY = 'REQUEST_SESSION_PUT_MONEY';
export const RECEIVED_SESSION_PUT_MONEY = 'RECEIVED_SESSION_PUT_MONEY';
export const RECEIVED_SESSION_PUT_MONEY_ERROR = 'RECEIVED_SESSION_PUT_MONEY_ERROR';

export const REQUEST_SESSION_TAKE_MONEY = 'REQUEST_SESSION_TAKE_MONEY';
export const RECEIVED_SESSION_TAKE_MONEY = 'RECEIVED_SESSION_TAKE_MONEY';
export const RECEIVED_SESSION_TAKE_MONEY_ERROR = 'RECEIVED_SESSION_TAKE_MONEY_ERROR';