export const STAFF_URL = `${process.env.APPLICATION_BFF_URL}`;
export const REQUEST_STAFF = 'REQUEST_STAFF';
export const RECEIVED_STAFF = 'RECEIVED_STAFF';
export const RECEIVED_STAFF_ERROR = 'RECEIVED_STAFF_ERROR';
export const REQUEST_STAFF_LIST = 'REQUEST_STAFF_LIST';
export const RECEIVED_STAFF_LIST = 'RECEIVED_STAFF_LIST';
export const RECEIVED_STAFF_LIST_ERROR = 'RECEIVED_STAFF_LIST_ERROR';
export const REQUEST_STAFF_UPDATE = 'REQUEST_STAFF_UPDATE';

export const RECEIVED_STAFF_UPDATE = 'RECEIVED_STAFF_UPDATE';

export const RECEIVED_STAFF_UPDATE_ERROR = 'RECEIVED_STAFF_UPDATE_ERROR';

