export const STORE_URL = `${process.env.APPLICATION_BFF_URL}`;
export const REQUEST_STORE = 'REQUEST_STORE';
export const RECEIVED_STORE = 'RECEIVED_STORE';
export const RECEIVED_STORE_ERROR = 'RECEIVED_STORE_ERROR';
export const REQUEST_STORE_POST = 'REQUEST_STORE_POST';
export const RECEIVED_STORE_POST = 'RECEIVED_STORE_POST';
export const RECEIVED_STORE_POST_ERROR = 'RECEIVED_STORE_POST_ERROR';
export const REQUEST_POS_LOGIN = 'REQUEST_POS_LOGIN';
export const RECEIVED_POS_LOGIN = 'RECEIVED_POS_LOGIN';
export const RECEIVED_POS_LOGIN_ERROR = 'RECEIVED_POS_LOGIN_ERROR';
export const CLEAR_POS_LOGIN = 'CLEAR_POS_LOGIN';

export const REQUEST_STORE_UPDATE = 'REQUEST_STORE_UPDATE';

export const REQUEST_ADDRESS_FROM_ZIP = 'REQUEST_ADDRESS_FROM_ZIP';
export const RECEIVED_ADDRESS_FROM_ZIP = 'RECEIVED_ADDRESS_FROM_ZIP';
export const RECEIVED_ADDRESS_FROM_ZIP_ERROR = 'RECEIVED_ADDRESS_FROM_ZIP_ERROR';
