export const USER_ROLE_URL = `${process.env.APPLICATION_BFF_URL}
/login/pos-login`;
export const REQUEST_USER_ROLE = 'REQUEST_USER_ROLE';
export const RECEIVED_USER_ROLE = 'RECEIVED_USER_ROLE';
export const RECEIVED_USER_ROLE_ERROR = 'RECEIVED_USER_ROLE_ERROR';
export const CLEAR_USER_ROLE = 'CLEAR_USER_ROLE';