export const MAIN_URL = `${process.env.APPLICATION_BFF_URL}`;

export const VENDOR_REQUEST = 'VENDOR_REQUEST';
export const VENDOR_RECIEVE_ERROR = 'VENDOR_RECIEVE_ERROR';
export const VENDOR_RECIEVE = 'VENDOR_RECIEVE';

export const VENDOR_FORM_REQUEST = 'VENDOR_FORM_REQUEST';
export const VENDOR_FORM_RECIEVE_ERROR = 'VENDOR_FORM_RECIEVE_ERROR';
export const VENDOR_FORM_RECIEVE = 'VENDOR_FORM_RECIEVE';

