export const MAIN_URL = `${process.env.APPLICATION_BFF_URL}`;

export const VENDOR_REQUEST = 'VENDOR_REQUEST';
export const VENDOR_RECIEVE_ERROR = 'VENDOR_RECIEVE_ERROR';
export const VENDOR_RECIEVE = 'VENDOR_RECIEVE';

export const VENDOR_FORM_REQUEST = 'VENDOR_FORM_REQUEST';
export const VENDOR_FORM_RECIEVE_ERROR = 'VENDOR_FORM_RECIEVE_ERROR';
export const VENDOR_FORM_RECIEVE = 'VENDOR_FORM_RECIEVE';

export const REQUEST_VENDOR_UPDATE = 'REQUEST_VENDOR_UPDATE';


export const REQUEST_REQUISITION_SAVE = 'REQUEST_REQUISITION_SAVE';
export const RECIEVE_REQUISITION_SAVE_ERROR = 'RECIEVE_REQUISITION_SAVE_ERROR';
export const RECIEVE_REQUISITION_SAVE = 'RECIEVE_REQUISITION_SAVE';

export const REQUEST_REQUISITION_LIST = 'REQUEST_REQUISITION_LIST';
export const RECIEVE_REQUISITION_LIST_ERROR = 'RECIEVE_REQUISITION_LIST_ERROR';
export const RECIEVE_REQUISITION_LIST = 'RECIEVE_REQUISITION_LIST';
