const dynamicActionWrapper = ({
    id,
    path,
    isFormData, 
    formData,
    method, 
    body, 
    headers, 
    initCb, 
    successCb, 
    failureCb,
    subreddit,
    wrapperActionType,
    mode,
    redirect,
    credentials,
    resolve,
    reject,
    cache,
    referrer,
    referrerPolicy,
    integrity,
    keepalive,
    signal,
    successCbPassOnParams,
  } ) => ({
    type: wrapperActionType,
    subreddit,
    id,
    successCbPassOnParams,
    fetchConfig: {
          path,
          method,
          isFormData,
          formData,
          body,
          headers,
          initHandler: initCb,
          success: successCb,
          failure: failureCb,
          resolve,
          reject,
          passOnParams: {
            mode,
            redirect,
            credentials,
            cache,
            referrer,
            referrerPolicy,
            integrity,
            keepalive,
            signal,
          }
      },
  });

  export default dynamicActionWrapper;
